### ISSUE TITLE
Register with OSSRH (to publish to maven central)

### ISSUE THREAD

**Issue by booniepepper** [so-dang-cool/z#4]
Register with OSSRH

https://central.sonatype.org/publish/publish-guide/

**Comment by madmikeross** [comment]
What is this about? Is this what it takes to upload repos to maven?

**Comment by booniepepper** [comment]
Yeah, the company Sonatype is the owner ("steward") of maven central, and this OSSRH thing is the way to get an account and credentials to publish to maven central

**Comment by booniepepper** [comment]
This should probably be a project instead of an issue - there are some things that go into it.

For example, I actually have to own the domain name that corresponds to the "group id." The convention is that the group id is the reverse of a domain name, so a group id of `com.google` corresponds to an actual domain of `google.com`

I'm aiming for a group ID of `so.dang.cool`. I own `*.dang.cool` and also the reverse `*.dang.so` and am setting up forwarding from the reverse to the normal one. I tried doing just a CNAME record , but it's failing to do what I want, so going to set up a more manual redirect tonight

**Comment by booniepepper** [comment]
Requesting registration here: https://issues.sonatype.org/browse/OSSRH-68968

**Comment by booniepepper** [comment]
Done
